version: '3.8'
name: hls
services:
  db:
    # container_name: 'db'
    build: 
      context: .
      dockerfile: db_Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my_net

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my_net
    depends_on:
      - db

volumes:
  db:

networks:
  my_net:
    driver: bridge
  